[2022-03-07T11:10:21.757435+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8000/"" at /home/cyril/Bureau/ORM/vendor/symfony/http-kernel/EventListener/RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8000/\" at /home/cyril/Bureau/ORM/vendor/symfony/http-kernel/EventListener/RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/cyril/Bureau/ORM/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:186)"} []
[2022-03-07T11:10:21.820408+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-03-07T11:10:21.924022+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"62f4ae"},"request_uri":"http://127.0.0.1:8000/_wdt/62f4ae","method":"GET"} []
[2022-03-07T15:38:42.173533+01:00] php.CRITICAL: Fatal Compile Error: Cannot declare class App\Entity\User, because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Cannot declare class App\\Entity\\User, because the name is already in use at /home/cyril/Bureau/ORM/src/Entity/User3.php:12)"} []
[2022-03-07T15:40:05.270618+01:00] php.CRITICAL: Fatal Compile Error: Cannot declare class App\Entity\User, because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Cannot declare class App\\Entity\\User, because the name is already in use at /home/cyril/Bureau/ORM/src/Entity/User3.php:12)"} []
[2022-03-07T15:47:13.962141+01:00] console.CRITICAL: Error thrown while running command "make:migration". Message: "An exception occurred in the driver: could not find driver" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)","command":"make:migration","message":"An exception occurred in the driver: could not find driver"} []
[2022-03-07T15:47:13.963204+01:00] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2022-03-07T16:13:00.758534+01:00] console.CRITICAL: Error thrown while running command "make:migration". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 1698): An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:119)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1698): SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 1698): SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)","command":"make:migration","message":"An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'"} []
[2022-03-07T16:13:00.761012+01:00] console.DEBUG: Command "make:migration" exited with code "1698" {"command":"make:migration","code":1698} []
[2022-03-07T16:34:18.593893+01:00] console.CRITICAL: Error thrown while running command "make:migration". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 1698): An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:119)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1698): SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 1698): SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)","command":"make:migration","message":"An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'"} []
[2022-03-07T16:34:18.595779+01:00] console.DEBUG: Command "make:migration" exited with code "1698" {"command":"make:migration","code":1698} []
[2022-03-07T16:37:00.035743+01:00] console.CRITICAL: Error thrown while running command "make:migration". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'cyril'@'localhost' (using password: NO)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1045): An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'cyril'@'localhost' (using password: NO) at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'cyril'@'localhost' (using password: NO) at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'cyril'@'localhost' (using password: NO) at /home/cyril/Bureau/ORM/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)","command":"make:migration","message":"An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'cyril'@'localhost' (using password: NO)"} []
[2022-03-07T16:37:00.037008+01:00] console.DEBUG: Command "make:migration" exited with code "1045" {"command":"make:migration","code":1045} []
